project:
  type: website

website:
  title: "Margherita Calderan"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd

format:
  html:
    theme: Sandstone
    css: style.css
    toc: true
