project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "home"
        href: index.qmd
      - text: "cv"
        href: cv.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

