project:
  type: website
  output-dir: docs

website:
  navbar:
    left:
      - text: "home"
        href: index.qmd
      - text: "cv"
        href: cv.qmd
      - text: "open-material"
        href: material.qmd
      - text: "contact"
        href: contact.qmd

format:
  html: 
    theme: solar
    fontsize: 1.1em
    linestretch: 1.7
    mainfont: Helvetica Neue
    css: styles.css
    toc: true

