---
title: "Test per le organizzazioni"
author: "Margherita Calderan & Ottavia M. Epifania"
date: last-modified
format:
  html:
    page-layout: full
    toc: true
    toc-location: right
    toc-depth: 3
    number-sections: true
    embed-resources: true
    css: styles.css
lang: it
execute:
  echo: true
  warning: false
  message: false
categories: [psicometrics, teaching]
---

Questo [documento](https://ottaviae.github.io/test-organizzioni-fisppa/dispensa/dispensa.html) raccoglie tutto il materiale del corso Test per le Organizzazioni.


::: callout-note
## Credits

-   Dispensa [Testing
    psicologico](https://ccaudek.github.io/testing_psicologico/) by
    Corrado Caudek
    
-   Brown, Anna. (2023). Psychometrics in Exercises using R and RStudio. Textbook and data resource. Available from <https://bookdown.org/annabrown/psychometricsR>.

-   Altoè, G. (2022). Corso di Testing Psicologico, Scienze psicologiche dello
sviluppo, della personalità e delle relazioni interpersonali, A.A. 2022/23

- Marci, M. (2025). Corso di Testing Psicologico, Scienze psicologiche dello
sviluppo, della personalità e delle relazioni interpersonali, A.A. 2025/26

Altri riferimenti utili sono:

-   Petersen, I. T. (2026). Principles of psychological assessment: With
    applied examples in R. Version 1.0.9. University of Iowa Libraries.
    <https://isaactpetersen.github.io/Principles-Psychological-Assessment>.
    <https://doi.org/10.25820/work.007199>

-   Martinková, P., & Hladká, A. (2023). Computational Aspects of
    Psychometric Methods: With R (1st ed.). Chapman and Hall/CRC.
    <https://doi.org/10.1201/9781003054313>
:::

